# Generated by Django 4.0.1 on 2022-01-23 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snblog', '0004_alter_post_image_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
